package com.epam.parsers;

public enum TariffTags {
    NAME, OPERATORNAME, PRICESMS, PAYROLL, INSIDECALLPRICE, OUTSIDECALLPRICE, STATIONARYCALLPRICE,
TARIFFICATION, CONNECTIONPRICE, HADFAVOURITENUMBER, tariff, PARAMETERS, CALLPRICES,
}
